// Centralized tour data for consistency across components
export interface Tour {
  id: number
  title: string
  image: string
  location: string
  region?: string
  duration: string
  groupSize: string
  price: string
  originalPrice?: string
  rating: number
  reviews?: number
  popular: boolean
  tag?: string | null
  description?: string
}

export const popularTours: Tour[] = [
  {
    id: 1,
    title: "Bangkok City Explorer",
    image: "/bangkok-grand-palace-temple-gold-thailand-sunny-da.jpg",
    location: "Bangkok",
    region: "central",
    duration: "3 Days",
    groupSize: "2-10",
    price: "฿8,500",
    originalPrice: "฿10,000",
    rating: 4.9,
    reviews: 234,
    popular: true,
    tag: "Best Seller",
    description: "Complete Bangkok experience including temples, markets, and nightlife.",
  },
  {
    id: 2,
    title: "Phuket Beach Paradise",
    image: "/phuket-beach-crystal-clear-water-tropical-paradise.jpg",
    location: "Phuket",
    region: "south",
    duration: "4 Days",
    groupSize: "2-8",
    price: "฿12,000",
    originalPrice: "฿15,000",
    rating: 4.8,
    reviews: 189,
    popular: true,
    tag: "Popular",
    description: "Relax on stunning beaches and explore Phi Phi Islands.",
  },
  {
    id: 3,
    title: "Chiang Mai Culture Trip",
    image: "/chiang-mai-temple-doi-suthep-golden-pagoda-thailan.jpg",
    location: "Chiang Mai",
    region: "north",
    duration: "3 Days",
    groupSize: "4-12",
    price: "฿9,500",
    originalPrice: "฿11,000",
    rating: 4.9,
    reviews: 312,
    popular: true,
    tag: "Top Rated",
    description: "Visit ancient temples and experience Lanna culture.",
  },
  {
    id: 4,
    title: "Krabi Island Hopping",
    image: "/krabi-four-islands-longtail-boat-limestone-cliffs-.jpg",
    location: "Krabi",
    region: "south",
    duration: "2 Days",
    groupSize: "2-6",
    price: "฿7,500",
    originalPrice: "฿9,000",
    rating: 4.7,
    reviews: 156,
    popular: false,
    tag: null,
    description: "Discover stunning islands, caves, and hidden lagoons.",
  },
]

export const allTours: Tour[] = [
  {
    id: 1,
    title: "Bangkok Grand Palace Tour",
    image: "/bangkok-grand-palace-temple-thailand.jpg",
    location: "Bangkok",
    region: "central",
    duration: "1 Day",
    groupSize: "2-15",
    price: "฿2,500",
    rating: 4.9,
    popular: true,
    description: "Explore the iconic Grand Palace, Wat Pho, and Wat Arun in one day.",
  },
  {
    id: 2,
    title: "Bangkok City Explorer",
    image: "/bangkok-city-skyline-river-thailand.jpg",
    location: "Bangkok",
    region: "central",
    duration: "3 Days",
    groupSize: "2-10",
    price: "฿8,500",
    rating: 4.8,
    popular: true,
    description: "Complete Bangkok experience including temples, markets, and nightlife.",
  },
  {
    id: 3,
    title: "Phuket Beach Paradise",
    image: "/phuket-beach-crystal-clear-water-thailand.jpg",
    location: "Phuket",
    region: "south",
    duration: "4 Days",
    groupSize: "2-8",
    price: "฿12,000",
    rating: 4.8,
    popular: true,
    description: "Relax on stunning beaches and explore Phi Phi Islands.",
  },
  {
    id: 4,
    title: "Chiang Mai Temple Trail",
    image: "/chiang-mai-temple-doi-suthep-thailand.jpg",
    location: "Chiang Mai",
    region: "north",
    duration: "3 Days",
    groupSize: "4-12",
    price: "฿9,500",
    rating: 4.9,
    popular: true,
    description: "Visit ancient temples and experience Lanna culture.",
  },
  {
    id: 5,
    title: "Krabi Island Hopping",
    image: "/krabi-four-islands-longtail-boat-thailand.jpg",
    location: "Krabi",
    region: "south",
    duration: "2 Days",
    groupSize: "2-6",
    price: "฿7,500",
    rating: 4.7,
    popular: false,
    description: "Discover stunning islands, caves, and hidden lagoons.",
  },
  {
    id: 6,
    title: "Pattaya Beach & Nightlife",
    image: "/pattaya-beach-city-thailand.jpg",
    location: "Pattaya",
    region: "east",
    duration: "2 Days",
    groupSize: "2-8",
    price: "฿5,500",
    rating: 4.5,
    popular: false,
    description: "Enjoy beaches, water sports, and vibrant nightlife.",
  },
  {
    id: 7,
    title: "Chiang Rai Golden Triangle",
    image: "/chiang-rai-white-temple-thailand.jpg",
    location: "Chiang Rai",
    region: "north",
    duration: "2 Days",
    groupSize: "4-10",
    price: "฿6,500",
    rating: 4.8,
    popular: false,
    description: "Visit White Temple and explore the Golden Triangle region.",
  },
  {
    id: 8,
    title: "Koh Samui Island Escape",
    image: "/koh-samui-beach-palm-trees-thailand.jpg",
    location: "Koh Samui",
    region: "south",
    duration: "5 Days",
    groupSize: "2-6",
    price: "฿18,000",
    rating: 4.9,
    popular: true,
    description: "Luxury beach escape with spa, snorkeling, and island tours.",
  },
  {
    id: 9,
    title: "Ayutthaya Historical Day Trip",
    image: "/ayutthaya-ancient-temple-ruins-thailand.jpg",
    location: "Ayutthaya",
    region: "central",
    duration: "1 Day",
    groupSize: "2-15",
    price: "฿2,800",
    rating: 4.7,
    popular: false,
    description: "Explore UNESCO World Heritage ancient temple ruins.",
  },
  {
    id: 10,
    title: "Hua Hin Royal Beach",
    image: "/hua-hin-beach-pier-thailand.jpg",
    location: "Hua Hin",
    region: "central",
    duration: "3 Days",
    groupSize: "2-8",
    price: "฿8,000",
    rating: 4.6,
    popular: false,
    description: "Experience royal Thai beach resort town with great seafood.",
  },
  {
    id: 11,
    title: "Khao Yai Nature Safari",
    image: "/khao-yai-national-park-wildlife-thailand.jpg",
    location: "Khao Yai",
    region: "northeast",
    duration: "2 Days",
    groupSize: "4-10",
    price: "฿6,000",
    rating: 4.8,
    popular: false,
    description: "Explore Thailand's first national park and spot wildlife.",
  },
  {
    id: 12,
    title: "Kanchanaburi River Kwai",
    image: "/kanchanaburi-bridge-river-kwai-thailand.jpg",
    location: "Kanchanaburi",
    region: "central",
    duration: "2 Days",
    groupSize: "4-12",
    price: "฿5,000",
    rating: 4.7,
    popular: false,
    description: "Visit the famous Bridge over River Kwai and Erawan Falls.",
  },
]
