// Centralized tour catalog for the home page, tour listing, and booking modal.
export interface Tour {
  id: number
  title: string
  image: string
  location: string
  region?: string
  duration: string
  groupSize: string
  price: string
  originalPrice?: string
  priceNote?: string
  rating: number
  reviews?: number
  popular: boolean
  homeFeatured?: boolean
  tag?: string | null
  description?: string
  highlights?: string[]
  includes?: string[]
  idealFor?: string
}

export const allTours: Tour[] = [
  {
    id: 1,
    title: "Bangkok Grand Palace Tour",
    image: "/bangkok-grand-palace-temple-thailand.jpg",
    location: "Bangkok",
    region: "central",
    duration: "1 Day",
    groupSize: "2-12",
    price: "฿3,400",
    originalPrice: "฿3,900",
    priceNote: "Per person, hotel pickup included",
    rating: 4.9,
    reviews: 168,
    popular: true,
    tag: "Top Rated",
    description: "A polished old-city day out covering the Grand Palace, Wat Pho, Wat Arun, and riverside viewpoints.",
    highlights: ["Grand Palace", "Wat Pho", "Wat Arun"],
    includes: ["Guide", "Hotel pickup", "Bottled water"],
    idealFor: "First-time Bangkok visitors",
  },
  {
    id: 2,
    title: "Bangkok City Explorer",
    image: "/bangkok-city-skyline-river-thailand.jpg",
    location: "Bangkok",
    region: "central",
    duration: "3 Days",
    groupSize: "2-10",
    price: "฿9,900",
    originalPrice: "฿11,500",
    priceNote: "Per person, based on twin share",
    rating: 4.9,
    reviews: 286,
    popular: true,
    homeFeatured: true,
    tag: "Best Seller",
    description: "Complete Bangkok experience with temples, street food, rooftop nights, and a relaxed Chao Phraya cruise.",
    highlights: ["Temple trio", "Night market", "Dinner cruise"],
    includes: ["3-star hotel", "Airport transfer", "Myanmar-speaking support"],
    idealFor: "Couples and short city breaks",
  },
  {
    id: 3,
    title: "Floating Market & Railway Discovery",
    image: "/bangkok-city-skyline-river-thailand.jpg",
    location: "Bangkok",
    region: "central",
    duration: "1 Day",
    groupSize: "2-12",
    price: "฿2,900",
    originalPrice: "฿3,300",
    priceNote: "Per person, shared transport",
    rating: 4.7,
    reviews: 102,
    popular: false,
    tag: "New Route",
    description: "A lively day trip to Maeklong Railway Market and Damnoen Saduak with easy pacing and good photo stops.",
    highlights: ["Railway market", "Boat ride", "Local snacks"],
    includes: ["Round-trip transport", "Boat ticket", "Guide support"],
    idealFor: "Families and content creators",
  },
  {
    id: 4,
    title: "Ayutthaya Historical Day Trip",
    image: "/ayutthaya-ancient-temple-ruins-thailand.jpg",
    location: "Ayutthaya",
    region: "central",
    duration: "1 Day",
    groupSize: "2-15",
    price: "฿3,200",
    originalPrice: "฿3,700",
    priceNote: "Per person, entrance tickets included",
    rating: 4.8,
    reviews: 143,
    popular: true,
    description: "Explore UNESCO-listed ruins, riverside temples, and Ayutthaya's laid-back historic quarter in one easy day.",
    highlights: ["Temple ruins", "UNESCO zone", "River views"],
    includes: ["Transport", "Tickets", "Lunch"],
    idealFor: "History lovers",
  },
  {
    id: 5,
    title: "Kanchanaburi River Kwai",
    image: "/kanchanaburi-bridge-river-kwai-thailand.jpg",
    location: "Kanchanaburi",
    region: "central",
    duration: "2 Days",
    groupSize: "4-10",
    price: "฿6,800",
    originalPrice: "฿7,600",
    priceNote: "Per person, based on twin share",
    rating: 4.8,
    reviews: 118,
    popular: false,
    description: "A thoughtful mix of wartime history, scenic river stays, and the emerald pools of Erawan.",
    highlights: ["River Kwai bridge", "Erawan Falls", "Train ride"],
    includes: ["1 hotel night", "Breakfast", "National park transfer"],
    idealFor: "Weekend escapes from Bangkok",
  },
  {
    id: 6,
    title: "Phuket Beach Paradise",
    image: "/phuket-beach-crystal-clear-water-thailand.jpg",
    location: "Phuket",
    region: "south",
    duration: "4 Days",
    groupSize: "2-8",
    price: "฿14,900",
    originalPrice: "฿16,800",
    priceNote: "Per person, resort stay included",
    rating: 4.8,
    reviews: 214,
    popular: true,
    homeFeatured: true,
    tag: "Popular",
    description: "A beach-forward Phuket package with island time, sunset viewpoints, and enough flexibility for cafe hopping.",
    highlights: ["Phi Phi cruise", "Beach club", "Sunset cape"],
    includes: ["3 hotel nights", "Island transfer", "Breakfast"],
    idealFor: "Friends and honeymoon-lite trips",
  },
  {
    id: 7,
    title: "Phuket Island Hopper",
    image: "/phuket-beach-paradise-thailand-aerial-view-crystal.jpg",
    location: "Phuket",
    region: "south",
    duration: "3 Days",
    groupSize: "2-8",
    price: "฿11,900",
    originalPrice: "฿13,500",
    priceNote: "Per person, island day trip included",
    rating: 4.7,
    reviews: 137,
    popular: false,
    description: "For travelers who want more sea time than city time, with premium speedboat access and soft-adventure pacing.",
    highlights: ["Island hopping", "Snorkeling", "Old Town stop"],
    includes: ["2 hotel nights", "Boat ticket", "Lunch on tour day"],
    idealFor: "Active beach travelers",
  },
  {
    id: 8,
    title: "Krabi Island Hopping",
    image: "/krabi-four-islands-longtail-boat-thailand.jpg",
    location: "Krabi",
    region: "south",
    duration: "2 Days",
    groupSize: "2-6",
    price: "฿6,900",
    originalPrice: "฿8,100",
    priceNote: "Per person, shared island tour included",
    rating: 4.8,
    reviews: 188,
    popular: true,
    homeFeatured: true,
    tag: "Top Rated",
    description: "A punchy Krabi itinerary with Four Islands, limestone cliff scenery, and relaxed beach downtime.",
    highlights: ["Four Islands", "Railay viewpoint", "Sunset beach"],
    includes: ["1 hotel night", "Boat transfer", "Lunch"],
    idealFor: "Short southern getaways",
  },
  {
    id: 9,
    title: "Koh Samui Island Escape",
    image: "/koh-samui-beach-palm-trees-thailand.jpg",
    location: "Koh Samui",
    region: "south",
    duration: "5 Days",
    groupSize: "2-6",
    price: "฿19,900",
    originalPrice: "฿22,500",
    priceNote: "Per person, premium resort plan",
    rating: 4.9,
    reviews: 126,
    popular: true,
    description: "A soft-luxury island break with spa time, snorkeling, and a polished balance of leisure and easy touring.",
    highlights: ["Resort stay", "Snorkeling", "Spa time"],
    includes: ["4 hotel nights", "Airport transfer", "Breakfast"],
    idealFor: "Couples and anniversary trips",
  },
  {
    id: 10,
    title: "Chiang Mai Culture Trip",
    image: "/chiang-mai-temple-doi-suthep-golden-pagoda-thailan.jpg",
    location: "Chiang Mai",
    region: "north",
    duration: "3 Days",
    groupSize: "4-12",
    price: "฿8,900",
    originalPrice: "฿10,200",
    priceNote: "Per person, temple and craft stops included",
    rating: 4.9,
    reviews: 327,
    popular: true,
    homeFeatured: true,
    tag: "Top Rated",
    description: "A warm northern itinerary built around temples, local crafts, coffee stops, and gentle cultural immersion.",
    highlights: ["Doi Suthep", "Old City", "Night bazaar"],
    includes: ["2 hotel nights", "Temple transport", "Breakfast"],
    idealFor: "Culture-first travelers",
  },
  {
    id: 11,
    title: "Doi Inthanon Highland Escape",
    image: "/chiang-mai-temple-mountain-sunset-thailand.jpg",
    location: "Chiang Mai",
    region: "north",
    duration: "2 Days",
    groupSize: "4-10",
    price: "฿7,400",
    originalPrice: "฿8,200",
    priceNote: "Per person, mountain route package",
    rating: 4.8,
    reviews: 104,
    popular: false,
    description: "Cool-air mountain touring with waterfalls, pagodas, and scenic stops around Thailand's highest peak.",
    highlights: ["Doi Inthanon", "Twin pagodas", "Waterfalls"],
    includes: ["1 hotel night", "Guide support", "Breakfast"],
    idealFor: "Nature lovers",
  },
  {
    id: 12,
    title: "Chiang Rai Golden Triangle",
    image: "/chiang-rai-white-temple-thailand.jpg",
    location: "Chiang Rai",
    region: "north",
    duration: "2 Days",
    groupSize: "4-10",
    price: "฿7,600",
    originalPrice: "฿8,700",
    priceNote: "Per person, includes White Temple route",
    rating: 4.8,
    reviews: 111,
    popular: false,
    description: "A north-bound route to the White Temple, Blue Temple, and the Golden Triangle border viewpoint.",
    highlights: ["White Temple", "Blue Temple", "Golden Triangle"],
    includes: ["1 hotel night", "Transport", "Breakfast"],
    idealFor: "Northern circuit add-ons",
  },
  {
    id: 13,
    title: "Khao Yai Nature Safari",
    image: "/khao-yai-national-park-wildlife-thailand.jpg",
    location: "Khao Yai",
    region: "northeast",
    duration: "2 Days",
    groupSize: "4-10",
    price: "฿6,800",
    originalPrice: "฿7,500",
    priceNote: "Per person, park transfer included",
    rating: 4.8,
    reviews: 97,
    popular: false,
    description: "Wildlife-spotting, scenic lookouts, and vineyard-style cafe stops just outside Bangkok's fast lane.",
    highlights: ["National park", "Wildlife route", "Cafe stop"],
    includes: ["1 hotel night", "Park transfer", "Breakfast"],
    idealFor: "Nature weekends",
  },
  {
    id: 14,
    title: "Pattaya Beach & Nightlife",
    image: "/pattaya-beach-city-thailand.jpg",
    location: "Pattaya",
    region: "east",
    duration: "2 Days",
    groupSize: "2-8",
    price: "฿6,200",
    originalPrice: "฿7,100",
    priceNote: "Per person, weekend plan",
    rating: 4.6,
    reviews: 94,
    popular: false,
    description: "A breezy Pattaya weekend built around beach time, dinner spots, and nightlife flexibility.",
    highlights: ["Beachfront stay", "Night market", "Water activity options"],
    includes: ["1 hotel night", "Breakfast", "Shared transfer"],
    idealFor: "Friends and quick escapes",
  },
  {
    id: 15,
    title: "Hua Hin Royal Beach",
    image: "/hua-hin-beach-pier-thailand.jpg",
    location: "Hua Hin",
    region: "central",
    duration: "3 Days",
    groupSize: "2-8",
    price: "฿8,700",
    originalPrice: "฿9,600",
    priceNote: "Per person, seaside stay included",
    rating: 4.7,
    reviews: 83,
    popular: false,
    description: "A slower-paced coastal plan with seafood evenings, market browsing, and beachside relaxation.",
    highlights: ["Night market", "Beachfront", "Seafood spots"],
    includes: ["2 hotel nights", "Breakfast", "Shared transfer"],
    idealFor: "Relaxed long weekends",
  },
]

export const popularTours: Tour[] = allTours.filter((tour) => tour.homeFeatured)
